#!/usr/bin/perl

###
# Copyright © http://edydkim.github.com            
#
# 
# This file is part of OctoKick.
# 
# OctoKick is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 3 of the
# License, or any later version.
# 
##

use strict;
use warnings;

use Expect;
use Data::Dumper;
use Getopt::Long;
use Pod::Usage;
     
my $host = 'host';
my $hostFile = '';
my $cmd = '';
my $user = '';
my $pw = '';
my $debug = 0;

# set options
sub options() {
	my $help = 0;

	# Process options.
	if (@ARGV > 0) {
     	    Getopt::Long::Configure ("bundling_override");
	    GetOptions('h=s'	=> \$host,
		       'f=s'	=> \$hostFile,
		       'help|?'	=> \$help,
		       'c=s'	=> \$cmd,
		       'u=s' => \$user,
		       'p=s' => \$pw,
		       'debug'	=> \$debug)
	    or pod2usage(2);
	}

	pod2usage(1) and exit 0 if $help;
}

# call expetc
sub expected() {
	my $exp = new Expect;
	$exp->log_file("octokick.log");
	$exp->log_stdout(0);
	$exp->raw_pty(1);
	
	my $cli = "ssh $user\@$host -o StrictHostKeyChecking=no -q $cmd";
	
	$exp->spawn($cli) or die "Cannot spawn $cli: $!\n";
	
	$exp->expect(5,
	 [ qr /ssword:*/ => sub { my $exph = shift;
	                          $exph->send("$pw\n");
	                          exp_continue; }] );
	
	my $read = $exp->exp_before();
	chomp $read;
	print ($read);
	# if use Dumper
	# print Dumper($read);
	
	$exp->soft_close();	
}


&options;

print "$cmd\n";

&expected;

1;
__END__
